[target.x86_64-unknown-linux-gnu]
pre-build = [
    "rustup update"
]

[target.armv7-unknown-linux-gnueabihf]
pre-build = [
    "rustup update"
]

[target.aarch64-unknown-linux-gnu]
pre-build = [
    "rustup update"
]