name: Build Odyssey

on:
  push:
  schedule:
    - cron: '0 0 * * *'
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: armv7-unknown-linux-gnueabihf
          components: clippy
          override: true

      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target armv7-unknown-linux-gnueabihf

      - uses: SebRollen/toml-action@v1.0.1
        id: read_toml
        with:
          file: 'Cargo.toml'
          field: 'package.version'

      - name: Copy & Compress output
        id: compress
        run: |
          NOW=$(date +"%Y-%m-%d-%H%M")
          ARCHIVE=$NOW-odyssey-${{ steps.read_toml.outputs.value }}
          cp target/armv7-unknown-linux-gnueabihf/release/odyssey odyssey
          cp target/armv7-unknown-linux-gnueabihf/release/odyssey.yaml odyssey.yaml
          tar -czvf $ARCHIVE.tar.gz  odyssey odyssey.yaml
          echo "archive=$ARCHIVE" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v3
        with:
          name: odyssey
          path: |
            odyssey
            odyssey.yaml

      - uses: ncipollo/release-action@v1
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/artifact_fix'
        with:
          artifacts: ${{ steps.compress.outputs.archive }}.tar.gz
          tag: v${{ steps.read_toml.outputs.value }}_test
          skipIfReleaseExists: true
          generateReleaseNotes: true
          commit: ${{github.sha}}
