name: Build Odyssey

on:
  push:
  schedule:
    - cron: '0 0 * * *'
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: armv7-unknown-linux-gnueabihf
          components: clippy
          override: true

      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target armv7-unknown-linux-gnueabihf

      - uses: actions/upload-artifact@v3
        with:
          name: odyssey
          path: |
            target/armv7-unknown-linux-gnueabihf/release/odyssey
            target/armv7-unknown-linux-gnueabihf/release/odyssey.yaml

      - uses: SebRollen/toml-action@v1.0.1
        id: read_toml
        with:
          file: 'Cargo.toml'
          field: 'package.version'

      - uses: ncipollo/release-action@v1
        if: github.ref == 'refs/heads/main'
        with:
          artifacts: target/armv7-unknown-linux-gnueabihf/release/odyssey,target/armv7-unknown-linux-gnueabihf/release/odyssey.yaml
          tag: v${{ steps.read_toml.outputs.value }}
          skipIfReleaseExists: true
          generateReleaseNotes: true
          commit: ${{github.sha}}
