name: Build Odyssey

on:
  push:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: armv7-unknown-linux-gnueabihf
          components: clippy
          override: true

      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target armv7-unknown-linux-gnueabihf

      - uses: SebRollen/toml-action@v1.0.1
        id: read_toml
        with:
          file: 'Cargo.toml'
          field: 'package.version'

      - name: Copy & Compress output
        id: compress
        run: |
          cp target/armv7-unknown-linux-gnueabihf/release/odyssey odyssey
          cp target/armv7-unknown-linux-gnueabihf/release/odyssey.yaml odyssey.yaml
          cp target/armv7-unknown-linux-gnueabihf/release/apiHelper.py apiHelper.py
          tar -czvf odyssey.tar.gz  odyssey odyssey.yaml apiHelper.py
          echo "archive=$ARCHIVE" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v3
        with:
          name: odyssey
          path: |
            odyssey
            odyssey.yaml
            apiHelper.py

      - uses: ncipollo/release-action@v1
        if: github.ref == 'refs/heads/main'
        with:
          artifacts: odyssey.tar.gz
          tag: v${{ steps.read_toml.outputs.value }}
          skipIfReleaseExists: true
          generateReleaseNotes: true
          commit: ${{github.sha}}
      - uses: ncipollo/release-action@v1
        if: github.ref != 'refs/heads/main'
        with:
          artifacts: odyssey.tar.gz
          tag: BRANCH_${{github.ref_name}}
          skipIfReleaseExists: false
          allowUpdates: true
          prerelease: true
          generateReleaseNotes: true
          commit: ${{github.sha}}
