name: Lint Odyssey

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Install Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: ""

      - name: Install Cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Clippy Linting
        run: cargo clippy --all-features

      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1