name: Pre-Push Format Check


on:
    push:
    workflow_call:
    workflow_dispatch:

jobs:
    pre-push:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Update Rust Toolchain
              uses: actions-rust-lang/setup-rust-toolchain@v1
              with:
                rustflags: ""
            
            - run: cargo fmt --all --check