name: Release Odyssey

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yml
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: SebRollen/toml-action@v1.0.1
        id: read_toml
        with:
          file: 'Cargo.toml'
          field: 'package.version'

      - uses: ncipollo/release-action@v1
        if: github.ref == 'refs/heads/main'
        with:
          artifacts: target/release/
          tag: v${{ steps.read_toml.outputs.value }}
          skipIfReleaseExists: true
          generateReleaseNotes: true
          commit: ${{github.sha}}

